lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/gcclock-words.js
      type: module

default_config:

demo:

binary_sensor:
  - name: github
    platform: ping
    host: github.com
