name: gcClock Words Continuous Integration

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check linting
        run: |
          npm install
          npm run check
