name: Uptime Card Continuous Integration

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check linting
        run: |
          npm install
          npm run check
